name: Test Web Scraper Automatically

on:
  push:
  schedule:
    - cron: "0 21 * * *"
  workflow_dispatch:

jobs:
  scraper:
    name: Run Instagram Web Scraper
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      # Install dependencies from root
      - name: Install dependencies
        run: npm install

      # Install dependencies from in playwright_scraper
      - name: Install dependencies
        run: npm install
        working-directory: playwright_scraper

      - name: Install Playwright dependencies
        run: npx playwright install
        working-directory: playwright_scraper

      - name: Enable Debugging Logs
        run: export DEBUG=pw:browser,pw:protocol

      - name: Run scraper
        # run: node playwright_scraper/instaScraper/instaScraper.js
        run: node playwright_scraper/easySite/easySiteScraper.js

      # - name: Upload Error Screenshot
      #   if: failure()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: error_screenshot
      #     path: playwright_scraper/instaScraper/error_screenshot.png

      # - name: Upload Error HTML
      #   if: failure()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: error_page
      #     path: playwright_scraper/instaScraper/error_page.html

      - name: Save Data
        uses: actions/upload-artifact@v4
        with:
          # name: instagramData
          # path: playwright_scraper/instaScraper/instagram.json
          name: easy-site-data
          path: playwright_scraper/easySite/easySite.json
