name: Test Web Scraper Automatically

schedule:
  - cron: "0 19 * * *"

jobs:
  scraper:
    name: Run Instagram Web Scraper
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "22.4.0"

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        run: node playwright_scraper/instaScraper/instaScraper.js

      - name: Save Data
        uses: actions/upload-artifact@v3
        with:
          name: instagramData
          path: playwright_scraper/instaScraper/instagram.json
