name: Test Web Scraper Automatically

on:
  push:
  schedule:
    - cron: "0 21 * * *"
  workflow_dispatch:

jobs:
  scraper:
    name: Run Instagram Web Scraper
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      # Install dependencies from root
      - name: Install dependencies
        run: npm install

      # Install dependencies from in playwright_scraper
      - name: Run scraper
        run: node playwright_scraper/instaScraper/instaScraper.js
        working-directory: playwright_scraper

      - name: Install Playwright dependencies
        run: npx playwright install-deps
        working-directory: playwright_scraper

      - name: Save Data
        uses: actions/upload-artifact@v3
        with:
          name: instagramData
          path: playwright_scraper/instaScraper/instagram.json
